### ISSUE TITLE
Клонирование, маусэвенты

### ISSUE THREAD

**Issue by srnden** [Nodlik/StPageFlip#2]
Приветствую. Есть пара моментов.
Я делаю что-то вроде фотоальбома, который заполняет пользователь своими фотографиями. Захотелось прикрутить смену разворотов перелистыванием страниц. Я попробовал вашу библиотеку и столкнулся с некоторыми проблемами.
У меня страница это дивка с канвасом, с которым надо взаимодействовать. При инициализации или окончании анимации у вас, для отображения текущего разворота, используются клонированные элементы. Я так понял, при клонировании канваса его содержимое не переносится. В общем, получаются пустые страницы. Я удалил клонирование из js и вроде все работает хорошо, я не увидел разницы.
Второй момент, нельзя отключить перелистывание с использованием мыши. То бишь, сделать так, чтобы можно было листать только по кнопкам где-нибудь внизу, а мышкой работать с моими канвасами:) Опять пришлось вручную удалять маусевенты.
С клонированием не знаю как правильно, но настройку для отключения маусэвентов можно прикрутить, думаю;)

**Comment by Nodlik** [comment]
Добрый день!
По поводу клонирования:
В процессе перелистывания в ландшафтном режиме используются четыре страницы: фиксированные правая и левая, перелистываемая страница и следующая под ней. Клонируются статичные на данный момент страницы (правая и левая). В портретном режиме - перелистываемая и статичная правая страница - одно и тоже, для этого и пришлось использовать клонирование. Соответственно - если его убрать, поломается портретный режим. 
Это конечно не самое лучшее решение, и, в принципе, есть понимание как можно от него избавится, и думаю в следующей версии его уже не будет...

Сейчас внес некоторые корректировки, пожалуйста, обновите до версии 1.2.0
При использовании флага "usePortrait: false" - будет отключен портретный режим и клонирование элементов
Добавлен флаг useMouseEvents, если установить его в false, то события мыши (и тач) не будут использоваться

**Comment by srnden** [comment]
Обновил, вроде всё хорошо;) Спасибо!
