### ISSUE TITLE
Screen resizing doesn't update the page dimensions

### ISSUE THREAD

**Issue by musaticsgilbert** [Nodlik/StPageFlip#22]
In the v2.0.5 update a change was made which broke the responsiveness of the book. 
Here is the problematic diff with exact line number: https://github.com/Nodlik/StPageFlip/commit/d9f209daf169bcb07ad9b5344e0ac96347d70d4b#diff-82e2514055cb74ebb7ad8048a1e13c101ca9276fe11790f259e165ac6eadd528L399

Putting the clearSaved methods and the two method calls in the update method seems to solve the issue.

**Comment by musaticsgilbert** [comment]
Update: dynamically adding new pages to the book breaks the resizing too because the resize handler is only set in the UI constructor and the updateItems method of HTMLUI removes every handler but only adds the mouse events back. Moving the window.onresize handler from the constructor to the start of the setHandlers method fixes this.

**Comment by Nodlik** [comment]
Fixed

**Comment by bytewyte** [comment]
Did you find any workaround? As of now it's not fixed for react.

**Comment by mohitkumawat310** [comment]
Did you find any workaround? As of now it's not fixed for react.
