### ISSUE TITLE
Remove shadow

### ISSUE THREAD

**Issue by L200150057** [Nodlik/StPageFlip#23]
How remove shadow in the left side of book?
btw i'm using "loadFromImages" method, so pageflip draw in canvas.

![Screenshot_4](https://user-images.githubusercontent.com/19193890/114865635-bea9bd00-9e1c-11eb-982e-e2ef73a212e8.png)

**Comment by zmskco** [comment]
hi, how do you remove the shadow?

**Comment by marooncoucal** [comment]
Hello, I know it's been a while, but could you explain or give directions as to where you managed to modify the shadow?

**Comment by L200150057** [comment]
## For Anyone Wanting to Remove the Book Shadow In The Middle of Book

Currently, the shadow is always drawn inside the canvas renderer with the method:

https://github.com/Nodlik/StPageFlip/blob/ab30ecc1d9f6d98de1a99b8e296469382f41c120/src/Render/CanvasRender.ts#L39

If you want to disable it, the quick solution is to **comment out this method call** in the drawFrame method and then rebuild the library.

---

### Cleaner Approach
A better solution would be to add a new parameter to disable the shadow
This way, developers can choose whether to render the shadow or not without touching the source code.

⚠️ ⚠️ I don’t have time to open a PR myself.  
If anyone does, please consider adding this parameter — it could be a small but useful improvement for the library. 😉
