### ISSUE TITLE
disable mouse over corner

### ISSUE THREAD

**Issue by rolexta** [Nodlik/StPageFlip#32]
https://github.com/Nodlik/StPageFlip/blob/927bb50a5d659c38a5cf3f6fa771db36cf7aa0ef/src/Flip/Flip.ts#L32

How to disable this event?, but when dragging the page still working

**Comment by rolexta** [comment]
i am sorry, my bad
solved by setting. showPageCorners to false

**Comment by cdk0507** [comment]
> i am sorry, my bad solved by setting. showPageCorners to false

Thank you for letting us know about this property.

Is there a way to use "showPageCorners" dynamically?

```
key={`flipbook-${pageScale}`}
showPageCorners={pageScale <= 1}
```

I tried re-rendering using key. But when I do this, the Flip event works.
