### ISSUE TITLE
Fire a onInit event on first load #FeatureRequest

### ISSUE THREAD

**Issue by jsoulet** [Nodlik/StPageFlip#4]
Hello,
I need to display additional data around my flipbook depending on the active page so I need to know which page is active, and if it has been loaded on landscape or portrait mode. Therefore, firing a "onInit" event on first load would be great.

Thank you

**Comment by Nodlik** [comment]
Hello,
Ok, you can try it now :). i added two events: 'init' and 'update'. You can use them like this:
<img width="608" alt="Снимок экрана 2020-08-15 в 18 39 04" src="https://user-images.githubusercontent.com/6822484/90315762-a2205280-df26-11ea-92d7-2957299e0a0a.png">
But! It is important to subscribe to this event before using the "loadFrom..." methods

**Comment by jsoulet** [comment]
Hi @Nodlik !
Thank you very much. Will it be available on the react-component too ?

**Comment by Nodlik** [comment]
Sorry for late answer. Now available! Please update
